import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { allPosts } from "contentlayer/generated";
import { pick } from "@contentlayer/client";

const Home: NextPage = () => {
  return (
    <div className="text-center flex justify-center flex-col place-items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="absolute top-36">
          <h1 className="font-bold text-6xl">Toby&apos;s blog</h1>
        </div>
    </div>
  )
}

export default Home
